# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '测试04afn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking'
  pod 'SDWebImage'
  # Pods for 测试04afn

  target '测试04afnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '测试04afnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
